# Generated by Django 3.1.2 on 2020-10-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201015_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='depart_div',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department'),
        ),
    ]
