# Generated by Django 3.1.2 on 2020-10-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceChars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('diagonal', models.IntegerField()),
                ('motherboard', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=20)),
                ('clock_frequency', models.FloatField()),
                ('ram_type', models.CharField(max_length=5)),
                ('ram_size', models.FloatField()),
                ('disk_space', models.CharField(max_length=50)),
                ('windows', models.CharField(max_length=50)),
                ('colour', models.BooleanField()),
                ('a3_tray', models.BooleanField()),
                ('inv_num', models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.device')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.device')),
            ],
        ),
    ]
