# Generated by Django 3.1.2 on 2020-10-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_device_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicechars',
            name='type',
        ),
    ]
