# Generated by Django 3.1.2 on 2020-10-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_devicechars_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicechars',
            name='brand_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='clock_frequency',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='diagonal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='disk_space',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='model_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='motherboard',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='processor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='ram_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='ram_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='windows',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
