# Generated by Django 3.1.2 on 2020-10-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201015_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicechars',
            name='a3_tray',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='colour',
            field=models.BooleanField(default=False),
        ),
    ]
