# Generated by Django 3.1.2 on 2020-10-18 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_auto_20201016_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inv_num',
            field=models.IntegerField(null=True, verbose_name='Інвентарний номер'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип пристрою'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Закріплений за'),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='a3_tray',
            field=models.BooleanField(default=False, verbose_name='Лоток А3'),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='clock_frequency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='colour',
            field=models.BooleanField(default=False, verbose_name='Кольоровий'),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='diagonal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Діагональ'),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='disk_space',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Об'єм диску"),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='motherboard',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материнська плата'),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='processor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Процесор'),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='ram_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Об'єм ОЗП"),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='ram_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Тип ОЗП'),
        ),
        migrations.AlterField(
            model_name='devicechars',
            name='windows',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Windows'),
        ),
    ]
